### ISSUE TITLE
Lot of repeated errors in *Messages* buffer

### ISSUE THREAD

**Issue by Compro-Prasad** [ema2159/centaur-tabs#3]
```
Invalid face reference: FontAwesome
Invalid face attribute :background nil [3 times]
```
The above message keeps on repeating itself after every redisplay.

**Comment by Compro-Prasad** [comment]
```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil)
Invalid face attribute :background nil [3 times]
```
Now I am getting above.

**Comment by ema2159** [comment]
> ```
> Invalid face reference: FontAwesome
> Invalid face attribute :background nil [3 times]
> ```
> 
> The above message keeps on repeating itself after every redisplay.

I'm aware of this one, it has to do with all-the-icons, that for some reason it doesn't consider FontAwesome in the messages buffer and just there I'm not quite sure why (notice it displays the wrong icon) although it displays the correct icon in my modeline. A temporary fix would be to exclude the messages buffer from the tabs while we find the cause and fix it.

**Comment by ema2159** [comment]
> ```
> Invalid face reference: FontAwesome
> Invalid face attribute :background nil [3 times]
> ```
> 
> The above message keeps on repeating itself after every redisplay.

I think I got this one at some point and it most likely has to do with one of the faces from centaur-tabs not having the background attribute. Do M-x describe-face and check if all of these have a background attribute:

``` emacs-lisp
centaur-tabs-selected
centaur-tabs-unselected
centaur-tabs-selected-modified
centaur-tabs-unselected-modified
```
This one is also related with all-the-icons (that in the yearly Emacs awards I'm sure it will get the award of the buggiest package ever created) because in order for the icons to have the correct background displayed the background has to be manually inserted in the icon.

**Comment by ema2159** [comment]
> ```
> Invalid face reference: FontAwesome
> Invalid face attribute :background nil [3 times]
> ```
> 
> The above message keeps on repeating itself after every redisplay.

I think the FontAwesome error is fixed in 5b7ef1aab890ed163e7405413c8be73b9fd3f126, please report me if you encounter it again. I'm sure the background nil error is a theming issue, the one that concerns me the most is the "Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil)" because I'm not getting it, are you still getting it @Compro-Prasad?

**Comment by Compro-Prasad** [comment]
The `Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil)` occurred when I was trying to debug the `FontAwesome` error. What is more striking is that, the `FontAwesome` error vanished and that error came in its place. Still can't debug the source of this error.

For all the faces: `Background: unspecified` is shown when I do `M-x describe-face`.

**Comment by ema2159** [comment]
> FontAwesome error is fixed btw.

Yes, I managed to find the cause and fix it.

> The `Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil)` occurred when I was trying to debug the `FontAwesome` error. What is more striking is that, the `FontAwesome` error vanished and that error came in its place. Still can't debug the source of this error.

I'm not having this error, it may have to do with the theme and the background error so lets fix that first. 
 
> For all the faces: `Background: unspecified` is shown when I do `M-x describe-face`.

Yes, just as I suspected. That has to do with your theme not having configured those faces. Two questions:

- Did you used the `centaur-tabs-inherit tabbar-faces` function?

- What theme do you have installed?

**Comment by Compro-Prasad** [comment]
Currently I don't have any theme enabled. So, its default Emacs theme.

**Comment by Compro-Prasad** [comment]
![Screenshot from 2019-06-29 07-54-33](https://user-images.githubusercontent.com/11143962/60378656-2d006e00-9a43-11e9-92ee-b46cd1a31490.png)

**Comment by ema2159** [comment]
Oh my god jajaja Vanilla Emacs is the ugliest thing in the universe! The thing is this, in order for the icons to work properly I had to do a kinda hackish fix (all the icons is really a troublesome package), so in order for the icons to work properly the centaur tabs selected/unselected need to have the background property specified. You can do it with this:
``` elisp
(set-face-attribute 'centaur-tabs-selected nil
		       :background (face-background '<<<YOUR-PROPER_BACKGROUND-HERE>>> nil t))
(set-face-attribute 'centaur-tabs-unselected nil
		       :background (face-background '<<<YOUR-PROPER_BACKGROUND-HERE>>> nil t))
```

**Comment by Compro-Prasad** [comment]
There seems a hard dependency on doom and tabbar. When I disabled `doom-modeline`, the tabs didn't show up. You need to inherit from Emacs specific default faces else there will always be errors for people who don't prefer doom specific setup.

**Comment by Compro-Prasad** [comment]
All errors are gone now. I am closing this issue for now. Will reopen when the issue reappears. Tabs look far better than previous ones. Thanks for the update.

**Comment by ema2159** [comment]
> There seems a hard dependency on doom and tabbar. When I disabled `doom-modeline`, the tabs didn't show up. You need to inherit from Emacs specific default faces else there will always be errors for people who don't prefer doom specific setup.

There's no hard dependency! It probably had to do with your config but it seems you fixed it

**Comment by ema2159** [comment]
> All errors are gone now. I am closing this issue for now. Will reopen when the issue reappears. Tabs look far better than previous ones. Thanks for the update.

Glad to know! Thank you for being this enthusiastic with my package!

**Comment by Compro-Prasad** [comment]
I am still getting:
```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil) [12 times]
```

**Comment by ema2159** [comment]
I'm still not having this error nor getting any other reports. Please check it's nothing from your side. You'll have to enable debug on error (do M-: `(setq debug-on-error t)`) and see the stack trace and then report this again.

**Comment by Compro-Prasad** [comment]
I byte compiled the file and it is working now without any issues. Thanks for the pointer.

**Comment by ema2159** [comment]
Awesome! Mr. @Compro-Prasad you've been till now my top 1 supporter and I really appreciate that jaja cheers man!

**Comment by Compro-Prasad** [comment]
Found the error. Actually, doom initialized all-the-icons. This was used by `centaur-tabs` to get icon. If the feature was unavailable, the function returned nothing. Will open a PR.

**Comment by dmitrym0** [comment]
Just had this happen on Emacs 27.2  (MacOS 12.3) with the latest MELPA centaur tabs. Disabling icons resolved the issue.
